language: rust

rust:
- 1.11.0

cache: cargo

script:
- |
  cargo build  --verbose &&
  cargo test   --verbose &&
  cargo doc    --verbose --no-deps &&
  cargo fmt    --verbose -- --write-mode=diff

# Thank's Johann! [ http://johannh.me/blog/rustfmt-ci.html ]
before_script: (cargo install rustfmt || true)

addons:
  apt:
    packages:
      - sqlite3
      - libsqlite3-dev
