language: rust

rust:
- nightly-2016-08-18

cache: cargo

script:
- |
  find $HOME -name rustfmt &&
  cargo fmt    --verbose -- --write-mode=diff &&
  cargo build  --verbose &&
  cargo test   --verbose &&
  cargo doc    --verbose --no-deps


# Thank's Johann! [ http://johannh.me/blog/rustfmt-ci.html ]
before_script: (cargo install rustfmt --root /home/travis/rust/bin || true)

addons:
  apt:
    packages:
      - sqlite3
      - libsqlite3-dev

